---
- hosts: dev
  become: True
  tasks:
    - name: install python pip
      yum:
        name: python-pip
        state: present
    - name: install docker py
      pip:
        name: docker-py
        state: present
    - name: install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: docker container
      docker_container:
        name: arpithcontainer
        image: arpithmadhusudan/javimg:1
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
